# Generated by Django 3.2.5 on 2021-09-29 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
